version: '3'
services:
  passphrase-api:
    image: node:14
    working_dir: /app
    volumes:
      - ./app.js:/app/app.js
      - ./generate_passphrases.sh:/app/generate_passphrases.sh
    ports:
      - 3000:3000
